const STORAGE_KEY = 'zhouya-erp-mvp-v1';
const state = loadState();
const $ = (id) => document.getElementById(id);
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved&&Array.isArray(saved.products)&&Array.isArray(saved.orders))return saved}catch(_){ }return{products:[],orders:[]}}
function saveState(message){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render();$('message').textContent=message||''}
function money(value){return new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format(value)}
function cell(row,value){const td=document.createElement('td');td.textContent=value;row.appendChild(td);return td}
function emptyRow(body,columns,value){const row=document.createElement('tr');const td=cell(row,value);td.colSpan=columns;td.className='empty';body.appendChild(row)}
function renderProducts(){const body=$('productRows'),select=$('orderSku');body.replaceChildren();select.replaceChildren();const prompt=document.createElement('option');prompt.value='';prompt.textContent=state.products.length?'请选择商品':'请先添加商品';select.appendChild(prompt);if(!state.products.length)emptyRow(body,6,'还没有商品，请先添加一个SKU。');state.products.forEach(product=>{const row=document.createElement('tr');cell(row,product.sku);cell(row,product.name);cell(row,String(product.stock));cell(row,String(product.alert));const status=cell(row,product.stock<=product.alert?'低库存':'正常');status.className=product.stock<=product.alert?'pill low':'pill';const action=document.createElement('td'),button=document.createElement('button');button.type='button';button.className='secondary inline-action';button.textContent='补货 +1';button.addEventListener('click',()=>{product.stock+=1;saveState(`${product.sku} 库存已增加 1。`)});action.appendChild(button);row.appendChild(action);body.appendChild(row);const option=document.createElement('option');option.value=product.sku;option.textContent=`${product.name}（${product.sku}，库存 ${product.stock}）`;select.appendChild(option)})}
function renderOrders(){const body=$('orderRows');body.replaceChildren();if(!state.orders.length)emptyRow(body,7,'还没有订单。');state.orders.slice().reverse().forEach(order=>{const row=document.createElement('tr');cell(row,order.orderNo);cell(row,`${order.productName} (${order.sku})`);cell(row,String(order.quantity));cell(row,money(order.amount));const status=cell(row,order.status);status.className=order.status==='已发货'?'pill done':'pill';cell(row,order.createdAt);const action=document.createElement('td');if(order.status==='待处理'){const button=document.createElement('button');button.type='button';button.className='secondary inline-action';button.textContent='标记发货';button.addEventListener('click',()=>{order.status='已发货';saveState(`${order.orderNo} 已标记为发货。`)});action.appendChild(button)}else action.textContent='—';row.appendChild(action);body.appendChild(row)})}
function render(){renderProducts();renderOrders();$('skuMetric').textContent=state.products.length;$('pendingMetric').textContent=state.orders.filter(order=>order.status==='待处理').length;$('revenueMetric').textContent=money(state.orders.reduce((sum,order)=>sum+order.amount,0));const low=state.products.filter(product=>product.stock<=product.alert).length;$('lowMetric').textContent=low;$('stockHint').textContent=low?`${low} 个商品需要补货`:'库存状态正常'}
$('productForm').addEventListener('submit',event=>{event.preventDefault();const sku=$('sku').value.trim().toUpperCase();if(state.products.some(product=>product.sku===sku)){$('message').textContent='这个SKU已经存在，请换一个编号。';return}state.products.push({sku,name:$('productName').value.trim(),stock:Number($('stock').value),alert:Number($('alertStock').value)});event.target.reset();$('stock').value=10;$('alertStock').value=3;saveState(`商品 ${sku} 已保存。`)})
$('orderForm').addEventListener('submit',event=>{event.preventDefault();const orderNo=$('orderNo').value.trim(),product=state.products.find(item=>item.sku===$('orderSku').value),quantity=Number($('quantity').value);if(state.orders.some(order=>order.orderNo===orderNo)){$('message').textContent='这个订单号已经存在。';return}if(!product||product.stock<quantity){$('message').textContent=product?`库存不足：${product.sku} 当前只有 ${product.stock} 件。`:'请选择商品。';return}product.stock-=quantity;state.orders.push({orderNo,sku:product.sku,productName:product.name,quantity,amount:Number($('amount').value),status:'待处理',createdAt:new Date().toLocaleString('zh-CN',{hour12:false})});event.target.reset();$('quantity').value=1;$('amount').value=0;saveState(`订单 ${orderNo} 已创建，库存已扣减。`)})
$('demoButton').addEventListener('click',()=>{if(state.products.length||state.orders.length){$('message').textContent='已有数据，未覆盖。需要重新体验可先清空全部数据。';return}state.products.push({sku:'MUG-WHITE',name:'白色马克杯',stock:8,alert:3},{sku:'BAG-CANVAS',name:'帆布袋',stock:2,alert:3});state.orders.push({orderNo:'ZY-DEMO-001',sku:'MUG-WHITE',productName:'白色马克杯',quantity:2,amount:59.8,status:'待处理',createdAt:new Date().toLocaleString('zh-CN',{hour12:false})});saveState('示例数据已载入，可以继续创建订单或标记发货。')})
$('exportButton').addEventListener('click',()=>{if(!state.orders.length){$('message').textContent='当前没有订单可导出。';return}const rows=[['订单号','SKU','商品','数量','金额','状态','创建时间'],...state.orders.map(o=>[o.orderNo,o.sku,o.productName,o.quantity,o.amount,o.status,o.createdAt])];const csv='\ufeff'+rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download=`zhouya-orders-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href);$('message').textContent='订单CSV已导出。'})
$('clearButton').addEventListener('click',()=>{if(!confirm('确定清空当前浏览器中的全部舟芽ERP数据吗？'))return;state.products=[];state.orders=[];saveState('全部本地数据已清空。')})
render();
